spring.application.name=HospitalManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDB
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create


#spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.data-location=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

#security-config

#spring.security.user.name=bunny
#spring.security.user.password=bunny

jwt.secretKey=wey347627%*&YGdyu2487fg@#^&havdgv$@3qehhsjdjfgyyfytfgufgld


