spring:
  security:
    oauth2:
      client:
        provider:
          twitter:
            authorization-uri: https://twitter.com/i/oauth2/authorize
            token-uri: https://api.twitter.com/2/oauth2/token
            user-info-uri: https://api.twitter.com/2/users/me
            user-name-attribute: id
        registration:
          google:
            client-id: 277796045980-o42sgk4qi4s7d365cepf8u8qlpsou36a.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: Ov23li93ptEQAXW09UbL
            client-secret: 83eec3189273c41eeaed6bb57f523b1b0111fed9
          twitter:
            client-id: =asdlfjasldf
            client-secret: asdlfjasldf
            redirect-uri: "{baseUrl}/login/oauth2/code/twitter"
            authorization-grant-type: authorization_code
            scope:
              - tweet.read
              - users.read
              - offline.access
            client-name: Twitter
            provider: twitter

